name: Alerta CI - Hola Mundo

on:
  push:
    branches:
      - main

jobs:
  notificacion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Ejecutar Hola Mundo
        run: node index.js

      - name: Enviar notificación a ntfy.sh
        run: |
          curl -X POST \
          -H "Title:  Push a main detectado" \
          -H "Priority: 4" \
          -d "Se ha subido código al branch main del repositorio ${{ github.repository }} por ${{ github.actor }}" \
          https://ntfy.sh/devops-itla
